#!/bin/sh

#####################################################################
# Nudge Removal Script
#####################################################################

# Current console user information
console_user=$(/usr/bin/stat -f "%Su" /dev/console)
console_user_uid=$(/usr/bin/id -u "$console_user")
userHomeDir=$(dscacheutil -q user | grep $console_user | awk 'NR==2 {print $2}')
deferralFile="$userHomeDir/Library/Preferences/com.github.macadmins.Nudge.plist"

# Force Quit Nudge
killall 'Nudge'

# Unload Launch Agent
sudo -u $console_user launchctl unload /Library/LaunchAgents/com.github.macadmins.Nudge.plist

# Remove Launch Agent
rm /Library/LaunchAgents/com.github.macadmins.Nudge.plist

# Remove Nudge
rm -r /Applications/Utilities/Nudge.app

# Only rm the preferences file if a user is logged in, otherwise fail
if [[ -z "$console_user" ]]; then
    echo "Did not detect user"
    exit 1
elif [[ "$console_user" == "loginwindow" ]]; then
    echo "Detected Loginwindow Environment"
    exit 1
elif [[ "$console_user" == "_mbsetupuser" ]]; then
    echo "Detect SetupAssistant Environment"
    exit 1
elif [[ "$console_user" == "root" ]]; then
    echo "Detect root as currently logged-in user"
    exit 1
else
    /bin/rm $deferralFile
    echo "Removed $deferralFile file"
fi

# Completion Message
echo "Nudge Removal Completed"

